language: c++

before_install:
  - sudo apt-get install python-software-properties -y
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update
  - sudo apt-get install haxe -y --force-yes
  - mkdir ~/haxelib
  - haxelib setup ~/haxelib
  - haxelib git openfl https://github.com/openfl/openfl
  - haxelib install openfl-native
  - haxelib install format
  - haxelib install svg
  - haxelib dev hxtools $(pwd)

script:
  - haxelib run openfl rebuild tools
  - haxelib run openfl
